# Generated by Django 5.2.5 on 2025-08-13 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=200, verbose_name='Modelo')),
                ('brand', models.CharField(max_length=200, verbose_name='Marca')),
                ('factory_year', models.IntegerField(blank=True, null=True, verbose_name='Ano de fabricação')),
                ('model_year', models.IntegerField(blank=True, null=True, verbose_name='Ano de modelo')),
                ('value', models.FloatField(blank=True, null=True, verbose_name='Valor')),
            ],
        ),
    ]
