# Generated by Django 5.2.5 on 2025-08-25 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_alter_car_plate_alter_car_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cars_count', models.IntegerField(verbose_name='Quantidade de carros')),
                ('cars_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Dos Carros')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
