# Generated by Django 5.2.5 on 2025-08-25 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_carinventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='carinventory',
            name='event_description',
            field=models.TextField(blank=True, null=True, verbose_name='Descricao do evento'),
        ),
    ]
